version: "3.9"

services:
  db:
    image: postgres:16.4
    restart: always
    shm_size: 128mb
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=testpw
      - POSTGRES_DB=testdb
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
